#!/usr/bin/env python3
"""
travel_assistant.py - 出行AI伴侣
基于酒店位置，支持自然语言关键字查询周边设施：
- 周边美食推荐
- 最近地铁站/公交站
- 附近有哪些银行/ATM
- 周边景区景点
- 综合出行配套报告

用法:
python scripts/travel_assistant.py --hotel "天津瑞湾开元名都" --lat 39.021567 --lon 117.745689 --query "周边有什么好吃的"
"""

import argparse
import os
import sys
from typing import List, Dict, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from industry_search.multi_industry import MultiIndustrySearcher, INDUSTRY_CATEGORIES

# ── 关键词映射 ─────────────────────────────────────────────

KEYWORD_MAPPING = {
    # 美食相关
    "好吃": ["餐饮"],
    "美食": ["餐饮"],
    "吃饭": ["餐饮"],
    "餐厅": ["餐饮"],
    "火锅": ["餐饮"],
    "烧烤": ["餐饮"],
    # 交通出行
    "地铁": ["出行"],
    "地铁站": ["出行"],
    "公交": ["出行"],
    "火车站": ["出行"],
    "机场": ["出行"],
    "交通": ["出行"],
    # 购物
    "购物": ["购物"],
    "商场": ["购物"],
    "超市": ["购物"],
    # 金融
    "银行": ["金融"],
    "ATM": ["金融"],
    "取钱": ["金融"],
    # 景点
    "景点": ["景区"],
    "景区": ["景区"],
    "公园": ["景区"],
    "玩": ["景区"],
    # 医疗
    "医院": ["医疗"],
    "药店": ["医疗"],
    # 全部
    "全部": list(INDUSTRY_CATEGORIES.keys()),
    "所有": list(INDUSTRY_CATEGORIES.keys()),
    "配套": list(INDUSTRY_CATEGORIES.keys()),
    "综合": list(INDUSTRY_CATEGORIES.keys()),
}


class TravelAssistant:
    """出行AI伴侣 - 基于酒店位置的周边查询助手"""

    def __init__(self, amap_api_key: str):
        self.searcher = MultiIndustrySearcher(api_key=amap_api_key)

    def set_hotel(self, name: str, lat: float, lon: float):
        """设置目标酒店"""
        self.searcher.set_hotel_location(name, (lon, lat))

    def parse_keyword_query(self, query: str) -> List[str]:
        """解析自然语言关键词，返回需要查询的分类"""
        categories = []
        query = query.lower()

        for keyword, cats in KEYWORD_MAPPING.items():
            if keyword in query:
                for cat in cats:
                    if cat not in categories:
                        categories.append(cat)

        if not categories:
            # 默认查餐饮+出行
            return ["餐饮", "出行"]

        return categories

    def generate_markdown_report(self, query: str, radius_km: float = 5.0) -> str:
        """生成Markdown格式出行报告"""
        categories = self.parse_keyword_query(query)
        report = self.searcher.generate_report(categories, radius_km=radius_km)

        lines = []
        lines.append(f"# 🧳 {self.searcher.hotel_name} - 出行配套查询")
        lines.append(f"**查询关键词**: {query}  \n")
        lines.append(f"**搜索范围**: {radius_km}km  \n")

        for cat, r in report["categories"].items():
            cfg = INDUSTRY_CATEGORIES[cat]
            icon = cfg["icon"]
            lines.append(f"\n## {icon} {cat} - {cfg['description']}")
            lines.append(f"- **总数**: {r.total_count}家")
            lines.append(f"- **3km内**: {r.nearby_count}家")
            lines.append(f"- **完善度**: {r.coverage_score}/100")
            if r.nearest:
                d = r.nearest.distance_km
                lines.append(f"- **最近**: {r.nearest.name} ({d:.1f}km)")
            # 列出前5家
            if r.all_pois:
                lines.append("\n近邻推荐:")
                for i, p in enumerate(r.all_pois[:5]):
                    d = p.distance_km
                    lines.append(f"  {i+1}. {p.name} ({d:.1f}km)")

        lines.append(f"\n---\n*generated by hotel-compete-report travel assistant*")
        return "\n".join(lines)

    def generate_html_report(self, query: str, radius_km: float = 5.0) -> str:
        """生成HTML格式出行报告（手机友好）"""
        categories = self.parse_keyword_query(query)
        report = self.searcher.generate_report(categories, radius_km=radius_km)

        html = []
        html.append("<!DOCTYPE html><html><head>")
        html.append("<meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>")
        html.append("<title>%s - 出行配套查询</title>" % self.searcher.hotel_name)
        html.append("<style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:800px;margin:0 auto;padding:15px;line-height:1.6}h1{color:#2c3e50;border-bottom:2px solid #eee;padding-bottom:10px}.category{background:#f8f9fa;border-radius:8px;padding:15px;margin:15px 0}.poi-item{padding:5px 0;border-bottom:1px solid #eee}.poi-distance{color:#666;font-size:0.9em}</style>")
        html.append("</head><body>")
        html.append("<h1>🧳 %s - 出行配套查询</h1>" % self.searcher.hotel_name)
        html.append("<p><strong>查询关键词:</strong> %s<br><strong>搜索范围:</strong> %gkm</p>" % (query, radius_km))

        for cat, r in report["categories"].items():
            cfg = INDUSTRY_CATEGORIES[cat]
            icon = cfg["icon"]
            html.append(f'<div class="category">')
            html.append(f'<h3>{icon} {cat} - {cfg["description"]}</h3>')
            html.append(f'<p>总数: {r.total_count}家<br>3km内: {r.nearby_count}家<br>完善度: {r.coverage_score}/100</p>')
            if r.nearest:
                d = r.nearest.distance_km
                html.append(f'<p><strong>最近:</strong> {r.nearest.name} ({d:.1f}km)</p>')
            if r.all_pois:
                html.append('<p><strong>推荐:</strong></p>')
                for i, p in enumerate(r.all_pois[:5]):
                    d = p.distance_km
                    html.append(f'<div class="poi-item">{i+1}. {p.name} <span class="poi-distance">({d:.1f}km)</span></div>')
            html.append('</div>')

        html.append("</body></html>")
        return "\n".join(html)


def main():
    parser = argparse.ArgumentParser(description="出行AI伴侣 - 酒店周边配套查询")
    parser.add_argument("--hotel", "-n", required=True, help="酒店名称")
    parser.add_argument("--lat", required=True, type=float, help="纬度")
    parser.add_argument("--lon", required=True, type=float, help="经度")
    parser.add_argument("--query", "-q", required=True, help="查询关键词（如：周边有什么好吃的）")
    parser.add_argument("--radius", "-r", type=float, default=5.0, help="搜索半径km")
    parser.add_argument("--output-dir", "-o", default="./travel_reports", help="输出目录")
    parser.add_argument("--api-key", "-k", help="高德API Key")
    args = parser.parse_args()

    api_key = args.api_key or os.environ.get("AMAP_MAPS_API_KEY", "0f9da10a87fa96c564f2d3d0f459fd6f")

    assistant = TravelAssistant(api_key)
    assistant.set_hotel(args.hotel, args.lat, args.lon)

    md = assistant.generate_markdown_report(args.query, args.radius)
    html = assistant.generate_html_report(args.query, args.radius)

    os.makedirs(args.output_dir, exist_ok=True)
    from slugify import slugify
    hotel_slug = args.hotel.replace(" ", "-").lower()
    query_slug = args.query[:20].replace(" ", "-").lower()

    md_path = os.path.join(args.output_dir, f"{hotel_slug}-{query_slug}.md")
    html_path = os.path.join(args.output_dir, f"{hotel_slug}-{query_slug}.html")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"\n✅ 报告生成完成!")
    print(f"   Markdown: {md_path}")
    print(f"   HTML: {html_path}")
    print(f"\n📝 预览:")
    print("-" * 60)
    print(md)


if __name__ == "__main__":
    main()
